### ISSUE TITLE
Review lpy json format

### ISSUE THREAD

**Issue by jvail** [fredboudon/plantgl-jupyter#11]
@fredboudon here are the relevant files https://github.com/jvail/plantgl-jupyter/tree/master/pgljupyter/schema

A few thoughts:

* Do you really need to support Bezier and Nurbs cuves? Is there something I can do with Bezier that I can not do with Nurbs?
* What about adding a required property like "unit" (what is the space unit in the lpy model? cm, m ...) to the schema?
* I have decided to use an object with properties rather than an array of objects. It has some advantages and disadvantages. A major disadvantage is sorting, ordering.

TODO
* versioning

**Comment by fredboudon** [comment]
Current lpy settings has the following part:
- setting version
- color map definition
- lpy studio settings (animation_timestep)
- lpy kernel settings (options)
- scalars parameters
    - Can be of type:
        - Category (just a name, type)
        - Bool (name, type, value)
        - Integer (name, type, value, min value, max value)
        - Float (name, type, value, min value, max value, step)
- graphical elements arranged in panels
    - Polyline, BezierCurve2D, NurbsCurve2D, Function, Patch
    - Panels with properties and list of graphical elements
        - properties: active, visible, name
- description
- authors

Some remarks based on my partial understanding of the current json files
- lpy.json: 
    - some elements seems to have disappeared such as 
        - setting version
        - lpy studio and kernel settings. We should discuss about that
        - the panels of graphical elements 
        - nurbspatches
        - description and authors (not so important)
    - you (re)introduced functions and curves but they are not always a good way to sort the parameters. However, the way lpy did it is also a bit constrained. Maybe new arrangement should be introduced
- scalars.json
    - It seems that you have reimplemented bool, integer, float. Maybe Category is missing. Or at least should be used for organizing parameters.
    - You introduced a property ‘category’. not clear for me.
- material.json, color.json, …
    - ok for me but maybe we need to look at it together.
