### ISSUE TITLE
LsystemWidget : bug with size_world

### ISSUE THREAD

**Issue by fredboudon** [fredboudon/plantgl-jupyter#20]
lw = LsystemWidget('mango_simulation.lpy', unit='cm', size_display=(800, 600), size_world=(5,5,5))
raise an error:
TraitError: The 'size_world' trait of a LsystemWidget instance expected an int, not the tuple (5, 5, 5).

**Comment by jvail** [comment]
Yes, I changed it from tuple to number. But it should be a float not an int.
