### ISSUE TITLE
Conda fetches outdated ipython version with py37 by default 

### ISSUE THREAD

**Issue by fredboudon** [fredboudon/plantgl-jupyter#26]
I just tested the installation procedure with pip.

I then run the following notebook:
https://github.com/fredboudon/fspm2020/blob/master/examples/Integration.ipynb
For the last cell I had the following error:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-00232cdb3480> in <module>()
----> 1 get_ipython().run_cell_magic('lpy', '-a True -u dm -w 4 -s 600,400', 'Axiom: \n    nproduce _(0.3)@Gc SetColor(Material((1,15,1),diffuse=10,specular=(0,0,0)))\n    for i in range(nbMetamers): nproduce I(i,0)/(137)[[&(40)L(i,0)]]\n    nproduce I(i,0) @O\n\nderivation length: int(maxTime//dt)\nproduction:\nI(i,t) --> I(i,t+dt)\nL(i,t) --> L(i,t+dt)\ninterpretation:\nI(i,t) --> F(internode_size(i,t))\nL(i,t) :\n    l = leaf_size(i,t)\n    nproduce SetColor(colors[i][0],colors[i][1],colors[i][2])_(0.1)&(t)F(l/6)[+(90)/(-30)~l(l/2)][-(90)/(30)~l(l/2)]F(l/6)[+(60)/(-15)~l(l/2)][-(60)/(15)~l(l/2)]F(l/6)^(20)~l(l/2)')

/Users/fboudon/Develop/miniconda3/envs/pgljupyter/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2115             magic_arg_s = self.var_expand(line, stack_depth)
   2116             with self.builtin_trap:
-> 2117                 result = fn(magic_arg_s, cell)
   2118             return result
   2119 

TypeError: lpy() missing 1 required positional argument: 'local_ns'
```

Note that I had to conda install sip  to avoid error from the ipython kernel and matplotlib for the notebook requirement.

**Comment by jvail** [comment]
Not sure what your ipython version is. Seems it is 6xx. The `local_ns` does not exists in this version:

https://github.com/ipython/ipython/blob/51ce9d73b29b9782d7f8a2f5d3d2af64a7ff37a0/IPython/core/interactiveshell.py#L2080-L2088

but it does in the version 7

https://github.com/ipython/ipython/blob/master/IPython/core/interactiveshell.py#L2360-L2377

I guess, that you must use a newer version of ipython. We should actually add it as a requirement.

**Comment by jvail** [comment]
Actually I have the same issue on linux if I do not explicitly specify python=3.8. With python 3.7 conda fetches a very outdated (5xx) version of ipython but I am able to update it. @fredboudon Do you have an outdated version in your lpy build?

**Comment by jvail** [comment]
If we can not remove this outdated dependency - I do not know from which pkg it comes - then this does work for me

`conda create -n pgl -c fredboudon -c conda-forge openalea.lpy jupyterlab ipywidgets ipython=7`
