### ISSUE TITLE
magic command to play a model

### ISSUE THREAD

**Issue by fredboudon** [fredboudon/plantgl-jupyter#28]
What about a new magic command to play a model ?
Something like
%%lpymodel fname parameters

**Comment by jvail** [comment]
Not exactly clear what this is supposed to do... please explain in a bit more detail.
I'd guess it could just be a line magic `%lpy` as well?

**Comment by fredboudon** [comment]
@jvail : Indeed reusing %%lpy could be a better idea.
Maybe an option -f fname could be good enough. The only question is what do we do with the rest of the code in the cell.
I also saw with julia that you have 2 commands : %%julia and %julia. The first one is used to create and compile julia code, the second to call some function from this julia env.
Maybe %lpy could be used for model defiend in a file.

**Comment by fredboudon** [comment]
What about introducing other options:
-i var1,var2,... (--input)        : variables to import in the model. default is all.
-inline : if the model should use the current namespace (requires small modification of lpy).
-o var1,var2,... (--output)    : variables to export out of the model. default is None.
-p varname (--parameters) : variable in which to export the parameter control.
-l varname (--lstring)           : variable in which the current lstring of the current view is exported. In case of an animation, only the last step is exported.
-m varname (--model)         : variable in which the current lsystem is exported.

**Comment by jvail** [comment]
@fredboudon  Is this obsolete?
