### ISSUE TITLE
Center view on scene if size not set explicitly

### ISSUE THREAD

**Issue by jvail** [fredboudon/plantgl-jupyter#31]
https://github.com/mrdoob/three.js/issues/18334

**Comment by jvail** [comment]
@fredboudon I tried the pgl bbox computer (bbox branch). Strangely it seems to work (in the leuwenberg example) for the trunk but after branching the bbox does not change anymore. Something wrong with my code?

**Comment by fredboudon** [comment]
I'm not sure how you use the bboxcomputer but by default it computes only the bbox of the last examined object. To have the bbox of an entire scene, you should do
bboxcomputer.process(scene);
BoundingBoxPtr result = bboxcomputer.getBoundingBox()

**Comment by jvail** [comment]
Please pull the latest from develop for testing. Seems to work for most of the examples in lpy share folder: If unit is not set explicitly then the scene will stay within the view of the camera - unless it has a very odd shape.
