### ISSUE TITLE
Provide parameter editors in %%lpy

### ISSUE THREAD

**Issue by jvail** [fredboudon/plantgl-jupyter#42]
@fredboudon 

Why not something like this

```py
# a simplified version of a param dict (with a different json schema, no tabs, no default Materials...)
import openalea.plantgl.all as pgl
params = {
	'an_int': [1, min, max, step],
	'a_float': [1.0, min, max, step],
	'a_func': [pgl.NurbsCurve2D([...]), True]
	}
}
```
Then ...

`%%lpy -p params`

We can save it in the default json file. If the file is loaded later **and** there is a parameter object we match names and types of the category named "params"

**Comment by fredboudon** [comment]
I'm not sure to see the point. You want user to specify their parameter manually ?

**Comment by jvail** [comment]
I thought we discussed a simplified version of the editor in case of cell magics ... the logic being:

- large models -> cell magic not usable & potentially many params -> full editor
- small models -> cell magic && just a few params -> minimal editor (also no "add/remove" buttons) 

minimal editor would be something like this ...

![image](https://user-images.githubusercontent.com/6503378/96224319-6e05f400-0fa0-11eb-8b21-407a9ece2427.png)
