### ISSUE TITLE
No name appearing with curve

### ISSUE THREAD

**Issue by fredboudon** [fredboudon/plantgl-jupyter#47]
Using commit c2e0d17e2b8e095bc45e035e151ae9d60a55d606 from magic-editor
The curves are not labelled with names.

**Comment by jvail** [comment]
That's strange. Seems to work for me. Did you rebuild the js and update the notebook/lab extension as well. Here is a minimal example that works for me:

```
lp = LsystemParameters()
lp.add('nurbs',NurbsCurve2D([(0,0,1),(0,1,1),(1,1,1),(1,0,1)]))
```

```
%%lpy -p lp
#
```

![image](https://user-images.githubusercontent.com/6503378/100306506-01c5d980-2fbd-11eb-9b09-ef776297c2d6.png)
