### ISSUE TITLE
PlantGL group shape not displayed

### ISSUE THREAD

**Issue by pomme-abricot** [fredboudon/plantgl-jupyter#52]
The SceneWidget object does not handle pgl.Group() shapes.
It does not display the groups and stop the display of the rest of the scene.

A small example:

`from math import radians
import openalea.plantgl.all as pgl
from pgljupyter import SceneWidget

length=1.
width=1.
disc = pgl.Translated((-0.5,0,0), pgl.Disc())
disc = pgl.Scaled((length, width,1), disc)
disc = pgl.AxisRotated(axis=(0,1,0), angle=radians(90.), geometry=disc)

d1 = pgl.AxisRotated(axis=(1,0,0), angle=-radians(60.), geometry=disc)
d2 = pgl.AxisRotated(axis=(1,0,0), angle=-radians(-60.), geometry=disc)

shape = pgl.Group([d1, d2])
SceneWidget(d1) # Works
SceneWidget(shape) # Display empty scene
`

**Comment by jvail** [comment]
Hi @pomme-abricot,

Thanks for reporting but it seems it is an issue in the PlantGL bgeom parser. I get these errors in the browser console:

```
*** PARSER: <Group : GEOMID_2482680320_94809590744232> A Geometry component is not valid. 95832a64-a482-4f82-a245-4b3c95c8b5a8:1:7026
Found unknown token value : 68
```
I suggest to open an issue over here https://github.com/fredboudon/plantgl. Or maybe test if you can properly encode and decode a pgl.Group to bgeom directly in PlantGL.

Meanwhile you could also just use `SceneWidget([d1, d2])`
