### ISSUE TITLE
Problem with scalar editor of derivation length

### ISSUE THREAD

**Issue by fredboudon** [fredboudon/plantgl-jupyter#55]
A graphical bug again. If I create a scalar that control the number of derivationLength to do, the lsystem is properly updated but not the LsystemWidget that continue to derive only with a minimal number of derivation.
Example
"""
import pgljupyter
from openalea.lpy.lsysparameters import LsystemParameters
params = LsystemParameters()
params.add_scalar('nbderiv',50)
"""
"""
%%lpy -p params -a True
Axiom: A(0)
derivation length: nbderiv
production:
A(t) --> A(t+1) 
interpretation:
A(t):
    print(t, nbderiv, __lsystem__.derivationLength)
    if t >= nbderiv:
        produce F(1)
"""

It would be nice to integrate the case where lsystem is derived the maximum number of steps, to derive the new number of steps:
https://github.com/jvail/plantgl-jupyter/blob/master/pgljupyter/widgets.py#L296
    
            previousderivLength = self.__lsystem.derivationLength+1
            self.__lsystem.clear()
            self.__lsystem.set(''.join([
                self.__codes[0],
                lp.generate_py_code()
            ]), self.__extra_context)
            self.derivationLength = self.__lsystem.derivationLength + 1
            self.__trees = []
            self.__trees.append(self.__lsystem.axiom)
            self.__derivationStep = self.__derivationStep if self.__derivationStep < previousderivLength else self.derivationLength - 1

**Comment by jvail** [comment]
@fredboudon I could not reproduce this anymore (or misunderstand the problem) with pgljupyter-2.0.0b0. If I move the slider forward then the widgets progress bar is adjusted accordingly and more derivations steps are available.
