### ISSUE TITLE
Problem with current derivation step nb

### ISSUE THREAD

**Issue by fredboudon** [fredboudon/plantgl-jupyter#56]
After first animation, getIterationNb() return always the derivation length and Start, StartEach, EndEach and End are no more called.
End is called at the previous to last step and Start is never called (shift of one for the derivation length ?)

**Comment by jvail** [comment]
@fredboudon Do you have a little example to illustrate the problem?

**Comment by fredboudon** [comment]
The following code illustrate the pb:

````
%%lpy -a True
nbiteration = 0

def Start():
  global nbiteration
  print('Start', getIterationNb(), nbiteration)
  assert getIterationNb() == nbiteration == 0


def StartEach():
  global nbiteration
  print('StartEach', getIterationNb(), nbiteration)
  assert getIterationNb() == nbiteration
  

def EndEach():
  global nbiteration
  print('EndEach', getIterationNb(), nbiteration)
  assert getIterationNb() == nbiteration
  if nbiteration != __derivation_length__-1:
    nbiteration += 1

def End():
  global nbiteration, __derivation_length__
  print('End', getIterationNb(), nbiteration)
  assert getIterationNb() == nbiteration == __derivation_length__-1

Axiom: A(0)

derivation length: 10
production:

A(t) --> A(t+1)

interpretation:


endlsystem
````

With standard lpy, it gives the following output:

````
Start 0 0
StartEach 0 0
EndEach 0 0
StartEach 1 1
EndEach 1 1
StartEach 2 2
EndEach 2 2
StartEach 3 3
EndEach 3 3
StartEach 4 4
EndEach 4 4
StartEach 5 5
EndEach 5 5
StartEach 6 6
EndEach 6 6
StartEach 7 7
EndEach 7 7
StartEach 8 8
EndEach 8 8
StartEach 9 9
EndEach 9 9
End 9 9
````

With pgljupyter, it simply gives:

````
StartEach 1 0
---------------------------------------------------------------------------
AssertionError  
````

**Comment by jvail** [comment]
@fredboudon
I think I found the issue (maybe came from the confusion if the axiom is derivation step 0 or not) but I still get an assertion in `End`. But maybe your example has an issue: Are you sure about:

`assert getIterationNb() == nbiteration-1 == __derivation_length__-1`

I'd guess it is 

`getIterationNb() == nbiteration == __derivation_length__-1`?

**Comment by jvail** [comment]
@fredboudon 
There is a new test version: pgljupyter-2.0.0b1 Please give it a try - I think it is fixed.
