### ISSUE TITLE
Compatibility with jupyterlab4

### ISSUE THREAD

**Issue by thomasarsouze** [fredboudon/plantgl-jupyter#64]
While `pgljupyter` is working fine with `jupyterlab=3.*`, `jupyterlab` has evolved to `v4.*`. As it is a major release, `pgljupyter` should be updated too (cf. this guide: https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html).

**Comment by thomasarsouze** [comment]
sorry to bother again @fredboudon and @jvail. Can you confirm that this is an actual issue of the package (and not an issue of my local setup) ? Any plan to check that ?

**Comment by jvail** [comment]
@thomasarsouze: this was working well for me (on debian) with jupyterlab 4: https://github.com/jvail/vmapplet/blob/master/binder/environment.yml

**Comment by thomasarsouze** [comment]
Indeed, now works on my side too... sorry for the noise !

**Comment by jvail** [comment]
No problem :) I know it can be annoying with all the possible combinations of libraries. Good that it works now!
